ambergris:
  image: ambergris/server
  privileged: true
  net: "host"
  links:
   - etcd
etcd:
  image: quay.io/coreos/etcd
  ports:
   - "2379:2379"
  command: -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379
  volumes:
   - ./default.etcd:/default.etcd
dlisten:
  image: bboreham/dlisten
  links:
   - etcd
  volumes:
   - /var/run/weave/weave.sock:/var/run/docker.sock
